version: '3.8'

services:
  catena:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catena_db
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    # Environment variables can also be passed here
    # environment:
    #   - DEBUG=true
